pipelines:
  branches:
    master:
    - step:
        size: 2x
        services:
          - docker
        caches:
          - docker
        script: # Modify the commands below to build your repository.
          - docker login --username $DOCKER_USERNAME --password $DOCKER_PASSWORD
          - docker build -f Dockerfile  -t chotavien/etest-online-web:dev .
          - docker push chotavien/etest-online-web:dev
    - step: 
        name: deploy to kubernates
        image: atlassian/pipelines-kubectl
        script: 
          - echo $KUBE_CONFIG | base64 -d > kubeconfig.yml
          - kubectl --kubeconfig=kubeconfig.yml rollout restart deployment/online-testing-deployment
definitions:
  services:
    docker:
      memory: 7128